spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankDB
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    user: postgres
    password: postgres
  sql:
    init:
      mode: always

server:
  error:
    include-message: always