ALTER TABLE IF EXISTS income ADD COLUMN operationType INTEGER;
ALTER TABLE IF EXISTS income ADD COLUMN dateOfOperation timestamp NOT NULL DEFAULT NOW();


ALTER TABLE IF EXISTS spend ADD COLUMN operationType INTEGER;
ALTER TABLE IF EXISTS spend ADD COLUMN dateOfOperation timestamp NOT NULL DEFAULT NOW();